name: Deploy Database Changes 

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Asegúrate de tener SQLAlchemy y Alembic en tu requirements.txt

    - name: Configure Alembic Environment
      run: |
        cd alembic
        echo "sqlalchemy.url = postgresql://${{ secrets.DATABASE_USER }}:${{ secrets.DATABASE_PASSWORD }}@${{ secrets.DATABASE_HOST }}:${{ secrets.DATABASE_PORT:-5432 }}/${{ secrets.DATABASE_NAME }}" > alembic.ini

    - name: Apply Alembic Migrations
      run: |
        cd alembic
        alembic upgrade head # Aplica todas las migraciones pendientes

    - name: Send Slack Notification (Optional)
      # ... (configuración de Slack)