name: Deploy Database Changes (PostgreSQL with Alembic)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Asegúrate de tener sqlalchemy, alembic y psycopg2 en este archivo

    - name: Configure Alembic Environment
      run: |
        cd alembic
         cat > alembic.ini <<EOL
        [alembic]
        sqlalchemy.url = postgresql://${{ secrets.DATABASE_USER }}:${{ secrets.DATABASE_PASSWORD }}@${{ secrets.DATABASE_HOST }}:${{ secrets.DATABASE_PORT}}/${{ secrets.DATABASE_NAME }}
        script_location = .

        [loggers]
        keys=root

        [handlers]
        keys=console

        [formatters]
        keys=generic

        [logger_root]
        level=INFO
        handlers=console

        [handler_console]
        class=logging.StreamHandler
        level=INFO
        formatter=generic
        args=(sys.stderr,)

        [formatter_generic]
        format=%(asctime)s %(levelname)-5.5s %(name)-20s %(message)s
        

        cat > alembic.ini <<EOL

    - name: Apply Alembic Migrations
      run: |
        cd alembic
        alembic upgrade head # Aplica todas las migraciones pendientes

